<?php
// ATTENTION, CE FICHIER N'EST QU'UN EXEMPLE. IL NE DOIT PAS ÊTRE UTILISÉ TEL QUEL.
// IL DEVRA ETRE REMPLACER PAR VOTRE PROPRE FICHIER CONFIG.PHP
// VOUS LE PLACEZ EN DEHORS DU DOSSIER 'www' (au dessus).
// Comme ça, personne ne peut le lire depuis internet.

define('GEMINI_API_KEY', 'VOTRE_CLE_API');